In [59]:
# Import de librairie
import pandas as pd
import numpy as np

# Database dechets par habitants

In [60]:
annees = [str(annee) for annee in range(2003, 2022)]

In [61]:
Data_dechets= []
for annee in annees:
    data_d = pd.read_excel(
        "Dechet_par_habitant.xls",
        sheet_name=annee,        
        skiprows=1,              
        usecols="A:B",          
        header=None,             
        names=["Commune", "Dechet_par_habitant_kg"]
    )
    data_d["Année"] = int(annee)     
    Data_dechets.append(data_d) 

Data_dechets_final = pd.concat(Data_dechets, ignore_index=True)

print(Data_dechets_final)
print(type(Data_dechets_final))

           Commune  Dechet_par_habitant_kg  Année
0    Aire-la-Ville              440.700000   2003
1          Anières              622.300000   2003
2           Avully              482.100000   2003
3            Avusy              447.900000   2003
4        Bardonnex              441.100000   2003
..             ...                     ...    ...
850        Troinex              464.605701   2021
851    Vandoeuvres              613.053812   2021
852        Vernier              408.657247   2021
853        Versoix              371.930217   2021
854        Veyrier              535.479049   2021

[855 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>

In [62]:
Data_dechets_final = Data_dechets_final [["Commune", "Année", "Dechet_par_habitant_kg"]]
Data_dechets_final = Data_dechets_final.sort_values(by=["Commune", "Année"])

Data_dechets_final = Data_dechets_final.reset_index(drop=True)

print(Data_dechets_final)

           Commune  Année  Dechet_par_habitant_kg
0    Aire-la-Ville   2003              440.700000
1    Aire-la-Ville   2004              442.000000
2    Aire-la-Ville   2005              389.200000
3    Aire-la-Ville   2006              388.700000
4    Aire-la-Ville   2007              377.500000
..             ...    ...                     ...
850        Veyrier   2017              458.800000
851        Veyrier   2018              403.400000
852        Veyrier   2019              377.400000
853        Veyrier   2020              426.000000
854        Veyrier   2021              535.479049

[855 rows x 3 columns]

In [63]:

dechet_moyennes_par_annee = Data_dechets_final.groupby('Année')['Dechet_par_habitant_kg'].mean().reset_index()
#print(dechet_moyennes_par_annee )

# Créer le dataframe des moyennes
dechet_moyennes =dechet_moyennes_par_annee.copy()
dechet_moyennes['Commune'] = 'Moyenne' 

Data_dechets_final = pd.concat([Data_dechets_final, dechet_moyennes], ignore_index=True)
print(Data_dechets_final)
Data_dechets_final = Data_dechets_final.sort_values(['Commune','Année'])
print(Data_dechets_final)

nombre_communes = Data_dechets_final["Commune"].nunique()
print(f"Nombre de communes : {nombre_communes}")

Data_dechets_final.to_csv("donnees_dechet_par_habitant.csv")

           Commune  Année  Dechet_par_habitant_kg
0    Aire-la-Ville   2003              440.700000
1    Aire-la-Ville   2004              442.000000
2    Aire-la-Ville   2005              389.200000
3    Aire-la-Ville   2006              388.700000
4    Aire-la-Ville   2007              377.500000
..             ...    ...                     ...
869        Moyenne   2017              441.768889
870        Moyenne   2018              432.253333
871        Moyenne   2019              435.862222
872        Moyenne   2020              443.968889
873        Moyenne   2021              457.900241

[874 rows x 3 columns]
           Commune  Année  Dechet_par_habitant_kg
0    Aire-la-Ville   2003              440.700000
1    Aire-la-Ville   2004              442.000000
2    Aire-la-Ville   2005              389.200000
3    Aire-la-Ville   2006              388.700000
4    Aire-la-Ville   2007              377.500000
..             ...    ...                     ...
850        Veyrier   2017              458.800000
851        Veyrier   2018              403.400000
852        Veyrier   2019              377.400000
853        Veyrier   2020              426.000000
854        Veyrier   2021              535.479049

[874 rows x 3 columns]
Nombre de communes : 46

# Database densité de la population

In [64]:
Data_densite = pd.read_excel("densité_de_la_population.xls")

Data_densite_reviewed = Data_densite.melt(id_vars=[Data_densite.columns[0]],var_name="Année", value_name="Densité_km2")
Data_densite_reviewed
Data_densite_reviewed.rename(columns={Data_densite.columns[0]: "Commune"}, inplace=True)

Data_densite_reviewed = Data_densite_reviewed.sort_values(by=["Commune", "Année"])

Data_densite_reviewed = Data_densite_reviewed .reset_index(drop=True)
Data_densite_reviewed

           Commune Année  Densité_km2
0    Aire-la-Ville  2005   286.000000
1    Aire-la-Ville  2006   311.000000
2    Aire-la-Ville  2007   374.000000
3    Aire-la-Ville  2008   383.000000
4    Aire-la-Ville  2009   389.000000
..             ...   ...          ...
895        Veyrier  2020  1829.000000
896        Veyrier  2021  1823.000000
897        Veyrier  2022  1836.000000
898        Veyrier  2023  1835.368468
899        Veyrier  2024  1858.764645

[900 rows x 3 columns]

In [65]:
densite_moyennes_par_annee = Data_densite_reviewed.groupby('Année')['Densité_km2'].mean().reset_index()

# Créer le dataframe des moyennes
densite_moyennes =densite_moyennes_par_annee.copy()
densite_moyennes

densite_moyennes['Commune'] = 'Moyenne' 
densite_moyennes
Data_densite_final = pd.concat([Data_densite_reviewed, densite_moyennes], ignore_index=True)
Data_densite_final = Data_densite_final.sort_values([ 'Commune','Année'])
print(Data_densite_final)
Data_densite_final.to_csv("donnee_densite_population.csv")

           Commune Année  Densité_km2
0    Aire-la-Ville  2005   286.000000
1    Aire-la-Ville  2006   311.000000
2    Aire-la-Ville  2007   374.000000
3    Aire-la-Ville  2008   383.000000
4    Aire-la-Ville  2009   389.000000
..             ...   ...          ...
895        Veyrier  2020  1829.000000
896        Veyrier  2021  1823.000000
897        Veyrier  2022  1836.000000
898        Veyrier  2023  1835.368468
899        Veyrier  2024  1858.764645

[920 rows x 3 columns]

# Database logement subventionné

In [66]:
annees = [str(annee) for annee in range(2009, 2025)]

Data_logement= []
for annee in annees:
    data_l = pd.read_excel(
        "Logement subventionnée.xls",
        sheet_name=annee,        
        skiprows=1,              
        usecols="A:B",          
        header=None,             
        names=["Commune", "Nombre_de_logements"]
    )
    data_l["Année"] = int(annee)     
    Data_logement.append(data_l) 

Data_logement_final = pd.concat(Data_logement, ignore_index=True)

Data_logement_final = Data_logement_final [["Commune", "Année", "Nombre_de_logements"]]



Data_logement_final = Data_logement_final.sort_values(by=["Commune", "Année"])


Data_logement_final = Data_logement_final.reset_index(drop=True)

print(Data_logement_final)

           Commune  Année Nombre_de_logements
0    Aire-la-Ville   2009                  24
1    Aire-la-Ville   2010                  24
2    Aire-la-Ville   2011                  24
3    Aire-la-Ville   2012                  24
4    Aire-la-Ville   2013                  24
..             ...    ...                 ...
715        Veyrier   2020                  87
716        Veyrier   2021                  87
717        Veyrier   2022                  87
718        Veyrier   2023                  87
719        Veyrier   2024                  87

[720 rows x 3 columns]

In [67]:
print(Data_logement_final['Nombre_de_logements'].dtype)
Data_logement_final['Nombre_de_logements'] = pd.to_numeric(Data_logement_final['Nombre_de_logements'], errors='coerce')
print(Data_logement_final['Nombre_de_logements'].dtype)


logement_moyennes_par_annee = Data_logement_final.groupby('Année')['Nombre_de_logements'].mean().reset_index()

# Créer le dataframe des moyennes
logement_moyennes =logement_moyennes_par_annee.copy()

logement_moyennes['Commune'] = 'Moyenne' 
print(logement_moyennes)
Data_logement_final = pd.concat([Data_logement_final, logement_moyennes], ignore_index=True)
Data_logement_final = Data_logement_final.sort_values(['Commune','Année'])
print(Data_logement_final)
Data_logement_final.to_csv("donnee_logement_subventionnee.csv")

object
float64
    Année  Nombre_de_logements  Commune
0    2009           546.861111  Moyenne
1    2010           539.305556  Moyenne
2    2011           519.702703  Moyenne
3    2012           515.675676  Moyenne
4    2013           558.212121  Moyenne
5    2014           618.533333  Moyenne
6    2015           660.071429  Moyenne
7    2016           584.064516  Moyenne
8    2017           566.281250  Moyenne
9    2018           581.656250  Moyenne
10   2019           592.125000  Moyenne
11   2020           614.156250  Moyenne
12   2021           658.406250  Moyenne
13   2022           660.406250  Moyenne
14   2023           704.838710  Moyenne
15   2024           737.600000  Moyenne
           Commune  Année  Nombre_de_logements
0    Aire-la-Ville   2009                 24.0
1    Aire-la-Ville   2010                 24.0
2    Aire-la-Ville   2011                 24.0
3    Aire-la-Ville   2012                 24.0
4    Aire-la-Ville   2013                 24.0
..             ...    ...                  ...
715        Veyrier   2020                 87.0
716        Veyrier   2021                 87.0
717        Veyrier   2022                 87.0
718        Veyrier   2023                 87.0
719        Veyrier   2024                 87.0

[736 rows x 3 columns]

# Database population

In [68]:
Data_pop = pd.read_excel("Population.xls")

Data_pop_final = Data_pop.melt(id_vars=[Data_densite.columns[0]],var_name="Année", value_name="Population_nombre-hbt")
Data_pop_final.rename(columns={Data_pop.columns[0]: "Commune"}, inplace=True)
Data_pop_final = Data_pop_final.sort_values(by=["Commune", "Année"])
Data_pop_final = Data_pop_final .reset_index(drop=True)
Data_pop_final.dropna()

Data_pop_final

            Commune Année  Population_nombre-hbt
0     Aire-la-Ville  2000                    711
1     Aire-la-Ville  2001                    713
2     Aire-la-Ville  2002                    710
3     Aire-la-Ville  2003                    736
4     Aire-la-Ville  2004                    727
...             ...   ...                    ...
1120        Veyrier  2020                  11880
1121        Veyrier  2021                  11842
1122        Veyrier  2022                  11936
1123        Veyrier  2023                  11924
1124        Veyrier  2024                  12076

[1125 rows x 3 columns]

In [69]:
population_moyennes_par_annee = Data_pop_final.groupby('Année')['Population_nombre-hbt'].mean().reset_index()

# Créer le dataframe des moyennes
population_moyennes =population_moyennes_par_annee.copy()

population_moyennes['Commune'] = 'Moyenne' 
len(population_moyennes)

Data_pop_final = pd.concat([Data_pop_final, population_moyennes], ignore_index=True)
Data_pop_final = Data_pop_final.sort_values([ 'Commune','Année'])
print(Data_pop_final)
Data_pop_final.to_csv("donnee_population.csv")

            Commune Année  Population_nombre-hbt
0     Aire-la-Ville  2000                  711.0
1     Aire-la-Ville  2001                  713.0
2     Aire-la-Ville  2002                  710.0
3     Aire-la-Ville  2003                  736.0
4     Aire-la-Ville  2004                  727.0
...             ...   ...                    ...
1120        Veyrier  2020                11880.0
1121        Veyrier  2021                11842.0
1122        Veyrier  2022                11936.0
1123        Veyrier  2023                11924.0
1124        Veyrier  2024                12076.0

[1150 rows x 3 columns]

# Prix m2

In [70]:
annees = [str(annee) for annee in range(2011, 2024)]

Data_prix= []
for annee in annees:
    data_p = pd.read_excel(
        "prix_m2_mediane.xls",
        sheet_name=annee,        
        skiprows=1,              
        usecols="A:B",          
        header=None,             
        names=["Commune", "prix_m2_marche_libre_Mediane"]
    )
    data_p["Année"] = int(annee)     
    Data_prix.append(data_p) 

Data_prix_final = pd.concat(Data_prix, ignore_index=True)

Data_prix_final = Data_prix_final [["Commune", "Année", "prix_m2_marche_libre_Mediane"]]



Data_prix_final = Data_prix_final.sort_values(by=["Commune", "Année"])


Data_prix_final = Data_prix_final.reset_index(drop=True)

print(Data_prix_final)

                                Commune  Année prix_m2_marche_libre_Mediane
0    Autres communes de l'Est du canton   2011                         7791
1    Autres communes de l'Est du canton   2012                         9830
2    Autres communes de l'Est du canton   2013                         7257
3    Autres communes de l'Est du canton   2014                         6941
4    Autres communes de l'Est du canton   2015                         6604
..                                  ...    ...                          ...
229                             Veyrier   2019                         9390
230                             Veyrier   2020                         8807
231                             Veyrier   2021                        10658
232                             Veyrier   2022                        10153
233                             Veyrier   2023                        10690

[234 rows x 3 columns]

In [71]:
print(Data_prix_final['prix_m2_marche_libre_Mediane'].dtype)
Data_prix_final['prix_m2_marche_libre_Mediane'] = pd.to_numeric(Data_prix_final['prix_m2_marche_libre_Mediane'], errors='coerce')
print(Data_prix_final['prix_m2_marche_libre_Mediane'].dtype)
prix_moyennes_par_annee = Data_prix_final.groupby('Année')['prix_m2_marche_libre_Mediane'].mean().reset_index()

# Créer le dataframe des moyennes
prix_moyennes =prix_moyennes_par_annee.copy()

prix_moyennes['Commune'] = 'Moyenne' 

print(len(prix_moyennes))

Data_prix_final = pd.concat([Data_prix_final, prix_moyennes], ignore_index=True)
Data_prix_final =Data_prix_final.sort_values([ 'Commune','Année'])
print(Data_prix_final)

Data_prix_final.to_csv("donnee_prix_m2_mediane.csv")

object
float64
13
                                Commune  Année  prix_m2_marche_libre_Mediane
0    Autres communes de l'Est du canton   2011                        7791.0
1    Autres communes de l'Est du canton   2012                        9830.0
2    Autres communes de l'Est du canton   2013                        7257.0
3    Autres communes de l'Est du canton   2014                        6941.0
4    Autres communes de l'Est du canton   2015                        6604.0
..                                  ...    ...                           ...
229                             Veyrier   2019                        9390.0
230                             Veyrier   2020                        8807.0
231                             Veyrier   2021                       10658.0
232                             Veyrier   2022                       10153.0
233                             Veyrier   2023                       10690.0

[247 rows x 3 columns]

# Revenu brute

In [72]:
annees = [str(annee) for annee in range(2010, 2019)]

Data_revenu= []
for annee in annees:
    data_r = pd.read_excel(
        "revenu_brut_annuel.xls",
        sheet_name=annee,        
        skiprows=1,              
        usecols="A:C",          
        header=None,             
        names=["Commune", "Médiane_couples_mariés", "Médiane_celibataire"]
    )
    data_r["Année"] = int(annee)     
    Data_revenu.append(data_r) 

Data_revenu_final = pd.concat(Data_revenu, ignore_index=True)

Data_revenu_final = Data_revenu_final [["Commune", "Année", "Médiane_couples_mariés", "Médiane_celibataire"]]



Data_revenu_final = Data_revenu_final.sort_values(by=["Commune", "Année"])


Data_revenu_final = Data_revenu_final.reset_index(drop=True)
Data_revenu_final

           Commune  Année  Médiane_couples_mariés  Médiane_celibataire
0    Aire-la-Ville   2010                  182788                56393
1    Aire-la-Ville   2011                  185509                61451
2    Aire-la-Ville   2012                  188721                58982
3    Aire-la-Ville   2013                  183835                60822
4    Aire-la-Ville   2014                  188643                62734
..             ...    ...                     ...                  ...
400        Veyrier   2014                  210336                51213
401        Veyrier   2015                  211323                52431
402        Veyrier   2016                  213176                53111
403        Veyrier   2017                  212835                52600
404        Veyrier   2018                  213093                52645

[405 rows x 4 columns]

In [73]:
indicateurs = ['Médiane_couples_mariés', 'Médiane_celibataire']
revenu_moyennes_par_annee = Data_revenu_final.groupby('Année')[indicateurs].mean().reset_index()
revenu_moyennes_par_annee

# Créer le dataframe des moyennes
revenu_moyennes =revenu_moyennes_par_annee.copy()

revenu_moyennes['Commune'] = 'Moyenne' 
print(len(revenu_moyennes))

Data_revenu_final = pd.concat([Data_revenu_final, revenu_moyennes], ignore_index=True)
Data_revenu_final =Data_revenu_final.sort_values([ 'Commune','Année'])
print(Data_revenu_final)
Data_revenu_final.to_csv("donnee_revenu_brut_annuel.csv")

9
           Commune  Année  Médiane_couples_mariés  Médiane_celibataire
0    Aire-la-Ville   2010                182788.0              56393.0
1    Aire-la-Ville   2011                185509.0              61451.0
2    Aire-la-Ville   2012                188721.0              58982.0
3    Aire-la-Ville   2013                183835.0              60822.0
4    Aire-la-Ville   2014                188643.0              62734.0
..             ...    ...                     ...                  ...
400        Veyrier   2014                210336.0              51213.0
401        Veyrier   2015                211323.0              52431.0
402        Veyrier   2016                213176.0              53111.0
403        Veyrier   2017                212835.0              52600.0
404        Veyrier   2018                213093.0              52645.0

[414 rows x 4 columns]

# Superficie communes

In [74]:
Data_superficie = pd.read_excel("superficie_par_communes.xls", names= ["Communes", "Superficie"])
Data_superficie.to_csv("donnee_superficie.csv")

# Données environnementales

In [75]:
Data_env =pd.read_csv("energyreporter_municipality_historized.csv")
Data_env_GE = Data_env.loc[Data_env["canton"]=="GE"]
Data_env_GE = Data_env_GE[["municipality","energyreporter_date",
                           "electric_cars_per_charging_spot","elec_consumption_mwh_per_year_per_capita",
                           "renelec_production_mwh_per_year_per_capita"]]
Data_env_GE

,municipality,energyreporter_date,electric_cars_per_charging_spot,elec_consumption_mwh_per_year_per_capita,renelec_production_mwh_per_year_per_capita
100264,Aire-la-Ville,2021-03-31,NaN,NaN,NaN
100265,Aire-la-Ville,2021-04-30,NaN,NaN,NaN
100266,Aire-la-Ville,2021-05-31,NaN,NaN,NaN
100267,Aire-la-Ville,2021-06-30,NaN,NaN,NaN
100268,Aire-la-Ville,2021-07-31,NaN,NaN,NaN
...,...,...,...,...,...
102464,Veyrier,2024-11-30,36.0,2.5447,0.5953
102465,Veyrier,2024-12-31,36.6,2.5535,0.5982
102466,Veyrier,2025-01-31,48.8,2.6138,0.5973
102467,Veyrier,2025-02-28,43.6,2.3159,0.6008
102468,Veyrier,2025-03-31,38.4,2.3037,0.5918

In [76]:
Data_env_final= Data_env_GE.dropna().reset_index(drop=True)
Data_env_final = Data_env_final.rename(columns={'municipality': 'Commune'})
Data_env_final = Data_env_final.rename(columns={'energyreporter_date': 'Année'})
Data_env_final.sort_values(by=["Commune", "Année"])
print(len(Data_env_final))

583

In [77]:
indicateurs_env = ['electric_cars_per_charging_spot', 'elec_consumption_mwh_per_year_per_capita', "renelec_production_mwh_per_year_per_capita"]
indicateurs_env_moyennes_par_annee = Data_env_final.groupby('Année')[indicateurs_env].mean().reset_index()
print(indicateurs_env_moyennes_par_annee)

# Créer le dataframe des moyennes
indicateurs_env_moyennes =indicateurs_env_moyennes_par_annee.copy()

indicateurs_env_moyennes['Commune'] = 'Moyenne' 
print(len(indicateurs_env_moyennes))

Data_env_final = pd.concat([Data_env_final, indicateurs_env_moyennes], ignore_index=True)
Data_env_final =Data_env_final.sort_values([ 'Commune','Année'])


Data_env_final.rename(columns={
    "electric_cars_per_charging_spot": "Voitures_electriques_par_borne",
    "elec_consumption_mwh_per_year_per_capita": "Consommation_electrique_annuelle_MWh_par_habitant",
    "renelec_production_mwh_per_year_per_capita": "Production_electrique_renouvelable_annuelle_MWh_par_habitant"
})

nombre_communes =Data_env_final["Commune"].nunique()
print(f"Nombre de communes : {nombre_communes}")

Data_env_final.to_csv("donnee_environement.csv")
Data_env_final

         Année  electric_cars_per_charging_spot  \
0   2023-11-30                        17.136667
1   2023-12-31                        16.918182
2   2024-01-31                        21.715152
3   2024-02-29                        15.596970
4   2024-03-31                        15.950000
5   2024-04-30                        15.790909
6   2024-05-31                        17.020588
7   2024-06-30                        18.860000
8   2024-07-31                        17.844118
9   2024-08-31                        17.844118
10  2024-09-30                        16.074286
11  2024-10-31                        16.005556
12  2024-11-30                        16.314286
13  2024-12-31                        17.030556
14  2025-01-31                        17.094444
15  2025-02-28                        17.516667
16  2025-03-31                        17.372222

    elec_consumption_mwh_per_year_per_capita  \
0                                   4.445170
1                                   4.453400
2                                   4.471927
3                                   4.457003
4                                   4.468935
5                                   4.409688
6                                   4.409474
7                                   4.388171
8                                   4.392679
9                                   4.371703
10                                  4.396063
11                                  4.370256
12                                  4.420069
13                                  4.406886
14                                  4.442983
15                                  3.941042
16                                  3.906019

    renelec_production_mwh_per_year_per_capita
0                                    31.852863
1                                    30.048485
2                                    30.843518
3                                    31.366830
4                                    31.525629
5                                    31.655303
6                                    31.481803
7                                    30.590686
8                                    31.475426
9                                    33.270476
10                                   31.598480
11                                   31.574247
12                                   33.413743
13                                   31.659958
14                                   31.194664
15                                   30.891839
16                                   30.500872
17
Nombre de communes : 38

,Commune,Année,electric_cars_per_charging_spot,elec_consumption_mwh_per_year_per_capita,renelec_production_mwh_per_year_per_capita
0,Aire-la-Ville,2023-11-30,8.5,3.4474,34.5596
1,Aire-la-Ville,2023-12-31,18.5,3.4965,34.5444
2,Aire-la-Ville,2024-01-31,20.0,3.5456,34.6373
3,Aire-la-Ville,2024-02-29,20.0,3.6118,34.5283
4,Aire-la-Ville,2024-03-31,6.8,3.6118,34.5596
...,...,...,...,...,...
578,Veyrier,2024-11-30,36.0,2.5447,0.5953
579,Veyrier,2024-12-31,36.6,2.5535,0.5982
580,Veyrier,2025-01-31,48.8,2.6138,0.5973
581,Veyrier,2025-02-28,43.6,2.3159,0.6008
582,Veyrier,2025-03-31,38.4,2.3037,0.5918